spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/carddb
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true

app:
  jwt:
    secret: jwt-secret-key
    expiration-ms: 86400000